[helper]
path = "out/nml_helper.f90"           # target path to create helper module (required)
module = "nml_helper"                 # module name to generate (optional)
buffer = 1024                         # line buffer length for helper module
header = '''
! created with nml-tools
'''

[constants]
[constants.max_iter]
value = 4
doc = "Maximum number of iterations."

[constants.buf]
value = 256
doc = "Buffer length for character strings."

[kinds]
module = "iso_fortran_env"            # module to use the kinds from
real = ["real32", "real64"]           # used real kinds
integer = ["int32", "int64"]          # used integer kinds
# mapping kind specifiers used in schema to Fortran kinds specified above
map = { sp = "real32", dp = "real64", i4 = "int32", i8 = "int64" }

[documentation]
module = '''
!> \version 0.1
'''

[[namelists]]
schema = "optimization.yml"           # schema defining the namelist file
mod_path = "out/nml_optimization.f90" # target path to create Fortran module
doc_path = "out/nml_optimization.md"  # target path to create documentation file

[[templates]]
output = "out/optimization.nml"
schemas = ["optimization.yml"]
doc_mode = "documented"      # or "plain"
value_mode = "filled"        # empty | filled | minimal-empty | minimal-filled

[templates.values.optimization]
niterations = 14
tolerance = 0.1
mcmc_error_params = [0.01, 0.6, 0.2, 0.6, 0.6, 0.6]
include_parameters = [true, false, true]
